name: Minigames
version: '${project.version}'
main: net.warofcivilizations.minigames.Minigames
api-version: 1.12
authors: [ poisontrigger ]
description: Minigames
commands:
  mini:
    description: Minigames
    usage: /Mini help
    permission: minigames.mini

